# Generated by Django 4.2.16 on 2024-09-28 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarket', '0002_alter_category_options_book_is_sale_book_sale_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='book',
            name='sale_price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=14),
        ),
    ]
